server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: ZUUL
  redis:
    host: 192.168.194.137
    port: 6379
    password: like
    database: 0

# zuul监控页面
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 忽略zuul通过网关访问提供方路径位置
zuul:
  ignored-services:
    - 'zuul'
  ignored-patterns: /zuul/*
#  # 自定义服务配置访问位置
#  routes:
#    webmaster:
#      path: /m/**
#      serverId: webmaster